import { useEffect,useState } from 'react'
import { ArrowLeft, BookOpen, Brain, FileText, Link2, MessageCircle, Send, Sparkles } from 'lucide-react'
import type { Topic } from '../topics/topic-data'
import {loadWorkspace,saveWorkspace} from '../../lib/storage'
import { sendChat, type ModelInfo } from '../models/model-api'
type Msg={id:number;role:'你'|'AI';text:string}
const tabs=[['讨论',MessageCircle],['感思',BookOpen],['资料',Link2],['纪要',FileText],['导图',Brain]] as const
export function WorkspaceView({topic,models,onBack}:{topic:Topic;models:ModelInfo[];onBack:()=>void}){
 const [tab,setTab]=useState('讨论');const [input,setInput]=useState('');const [note,setNote]=useState('');const [selectedModel,setSelectedModel]=useState('siyu-demo');const [sending,setSending]=useState(false);const [error,setError]=useState('');const [msgs,setMsgs]=useState<Msg[]>(()=>loadWorkspace(topic.id,{msgs:[] as Msg[]}).msgs)
 useEffect(()=>saveWorkspace(topic.id,{msgs,note}),[topic.id,msgs,note])
 async function send(){const value=input.trim();if(!value||sending)return;const userMessage={id:Date.now(),role:'你' as const,text:value};const next=[...msgs,userMessage];setMsgs(next);setInput('');setSending(true);setError('');try{const content=await sendChat(selectedModel,next.map(message=>({role:message.role==='你'?'user' as const:'assistant' as const,content:message.text})));setMsgs(current=>[...current,{id:Date.now()+1,role:'AI',text:content}])}catch(cause){setError(cause instanceof Error?cause.message:'模型请求失败')}finally{setSending(false)}}
 return <main className="workspace"><header className="workspace-head"><button className="icon-button" onClick={onBack} aria-label="返回今日议题"><ArrowLeft/></button><div><span>{topic.kind} · 思考空间</span><h1>{topic.title}</h1></div><span className="saved">● 已保存</span></header>
 <nav className="tabs" aria-label="思考空间视图">{tabs.map(([name,Icon])=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}><Icon size={17}/>{name}</button>)}</nav>
 {tab==='讨论'?<div className="workspace-grid"><section className="conversation"><div className="modelbar"><label><Sparkles size={15}/><select aria-label="选择对话模型" value={selectedModel} onChange={event=>setSelectedModel(event.target.value)}>{models.map(model=><option key={model.id} value={model.id} disabled={!model.available}>{model.provider} · {model.name}{!model.available?'（待配置）':''}</option>)}</select></label><span>{models.find(model=>model.id===selectedModel)?.demo?'演示模式':'真实 API'} · 当前议题</span></div><div className="messages">{msgs.length===0?<div className="opening"><span>从这里开始</span><h2>你对这个问题最初的直觉是什么？</h2><p>不用急着给出完整答案，先写下此刻最真实的判断。</p></div>:msgs.map(m=><article className={`message ${m.role==='AI'?'ai':''}`} key={m.id}><b>{m.role}{m.role==='AI'&&<small> · {models.find(model=>model.id===selectedModel)?.name}</small>}</b><p>{m.text}</p></article>)}</div>{error&&<p className="chat-error" role="alert">{error} · 你的消息已保留，可以配置后重试。</p>}<div className="composer"><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="写下你的想法……" aria-label="对话内容"/><div><span>{sending?'正在思考…':'Enter 发送 · Shift + Enter 换行'}</span><button disabled={sending} onClick={send} aria-label="发送消息"><Send size={18}/></button></div></div></section><aside className="notes"><span className="eyebrow">私人旁注</span><h2>只写给自己</h2><p>默认不会发送给 AI，也不会自动进入纪要。</p><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="记下犹豫、灵感或还没想清楚的部分……"/></aside></div>:<Panel tab={tab}/>}</main>}
function Panel({tab}:{tab:string}){const copy:Record<string,[string,string]>= {感思:['写下此刻的感思','保留你的原文，也可以稍后邀请 AI 协助整理。'],资料:['议题资料','收藏来源、引用与待核实的信息。'],纪要:['本次思考纪要','核心观点：工具不会简单取代记忆，而会改变我们选择记住什么。\n\n未解决问题：当外部记忆随时可用，人的身份连续性如何形成？'],导图:['思维导图','议题\n├─ 核心观点\n│  ├─ 记忆外包\n│  └─ 主动组织\n├─ 反对理由\n└─ 未解决问题']};return <section className="panel"><span className="eyebrow">{tab==='纪要'?'AI 整理 · 演示内容':'思考空间'}</span><h2>{copy[tab][0]}</h2><p className={tab==='导图'?'tree':''}>{copy[tab][1]}</p>{tab==='感思'&&<textarea placeholder="从一句还不完整的话开始……"/>}</section>}
